# Same as Dockerfile (Network Volume for models).
FROM runpod/worker-comfyui:5.8.5-base

ARG HF_TOKEN=""
ENV HUGGINGFACE_TOKEN=${HF_TOKEN}
ENV HUGGINGFACE_ACCESS_TOKEN=${HF_TOKEN}

RUN comfy-node-install https://github.com/ltdrdata/ComfyUI-Impact-Pack
RUN comfy-node-install https://github.com/rgthree/rgthree-comfy
RUN comfy-node-install https://github.com/TTPlanetPig/Comfyui_TTP_Toolset
RUN comfy-node-install https://github.com/kijai/ComfyUI-KJNodes
RUN comfy-node-install https://github.com/yolain/ComfyUI-Easy-Use
RUN comfy-node-install https://github.com/EvilBT/ComfyUI_SLK_joy_caption_two

COPY extra_model_paths.yaml /comfyui/extra_model_paths.yaml

COPY scripts/start_with_runpod_volume.sh /usr/local/bin/start_with_runpod_volume.sh
RUN chmod +x /usr/local/bin/start_with_runpod_volume.sh

CMD ["/usr/local/bin/start_with_runpod_volume.sh"]

# Optional: other models (commented out)
# RUN comfy model download --url https://huggingface.co/shiertier/clip_vision/resolve/main/SD15/model.safetensors --relative-path models/clip_vision --filename models.safetensors
# RUN comfy model download --url https://huggingface.co/lllyasviel/ic-light/resolve/main/iclight_sd15_fcon.safetensors --relative-path models/diffusion_models --filename iclight_sd15_fcon.safetensors
# COPY input/ /comfyui/input/
# RUN comfy model download --set-hf-api-token ${HF_TOKEN} --url https://huggingface.co/camenduru/SUPIR/resolve/main/SUPIR-v0F.ckpt?download=true --relative-path models/upscale_models --filename SUPIR-v0F.ckpt
